[wokwi]
version = 1
board = "esp32dev"
project = "."
diagram = "diagram.json"
firmware = ".pio/build/esp32dev/firmware.bin"

[[net.forward]]
from = "wokwi"
to = "api.telegram.org:443"

[[net.forward]]
from = "wokwi"
to = "api.thingspeak.com:80"